开发中，有一种情况是这样的，A，B 2个类都是加了事务管理的，类A其中一个方法methedA调用了另个一个类B的方法methedB，类B的methedB抛出了一个异常，methedA对异常进行了捕获，这个人try catch的本意是当methedB出异常的时候不care，当真实的结果是这时候事物会会滚。

```java
@Service
@Transactional(rollbackFor = Exception.class)
public class AService implements IInvoiceLoggingService {
  
@Autowired
private BService bService;
  
public void methedA() {
  try {
  			bService.methedB();
  } catch (Exception ignored) {
    // log
  }
  }
}

@Service
@Transactional(rollbackFor = Exception.class)
public class BService implements IInvoiceLoggingService {

public void methedB() {
  //doSomething;
}
```



A方法加@Transactional, B方法加@Transactional 此时B的传播特性为:Propagation.REQUIRED,
B方法会使用A的事务,当B方法throw时,会把事务标记为回滚,因此A也会回滚,catch没用,

解决:
B方法的传播特性可以为:NESTED, 嵌套事务即可;这样B的事务会独立起来;A的事务不会跟着回滚;

